# Dev 分支推送部署预览
## 仅部署 Win 端
name: Build Dev

on:
  push:
    branches:
      - bw

  workflow_dispatch:

jobs:
  release:
    name: Build Website
    runs-on: windows-latest

    permissions:
      id-token: write # 用于 Deno Deploy 进行身份验证
      contents: read # 用于克隆存储库

    steps:
      # 检出 Git 仓库
      - name: Check out git repository
        uses: actions/checkout@v4.1.7

      # 安装 Deno
      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.7.0

      # 安装 Node.js
      - name: Install Node.js
        uses: actions/setup-node@v4.0.3
        with:
          node-version: "18.x"

      # 复制环境变量文件
      - name: Copy .env.example
        run: |
          if (-not (Test-Path .env)) {
            Copy-Item .env.example .env
          } else {
            Write-Host ".env file already exists. Skipping the copy step."
          }

      # 安装项目依赖
      - name: Install Dependencies
        run: npm install

      # 构建程序
      - name: Build Website
        run: npm run build
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      # 上传构建产物
      - name: Upload Artifact
        uses: actions/upload-artifact@v4.3.4
        with:
          name: HomePage
          path: dist
      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "bw-homepage" # 提交到 Deno Deploy 的项目 ID
          entrypoint: "https://deno.land/std@0.188.0/http/file_server.ts"
          root: "dist"
